server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:sun;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.time_zone: UTC
  h2:
    console:
      enabled: true
      path: /h2

logging:
  level:
    root: info
    org.springframework.web.reactive.function.client: info

app:
  sun-api:
    base-url: https://api.sunrisesunset.io    # ajustaremos se necessário
    timeout-ms: 10000
  geocode:
    base-url: https://nominatim.openstreetmap.org
    timeout-ms: 10000
    user-agent: sunrise-sunset-demo/1.0 (contact:[email protected])
